### ISSUE TITLE
How to install it in windows? 

### ISSUE THREAD

**Issue by Droyk** [kylemcdonald/FreeWifi#15]

**Comment by kylemcdonald** [comment]
I don't have a copy of Windows to test on, but I'm happy to provide some advice if you can follow the steps as best you can, and tell me what is working for you so far.

**Comment by Droyk** [comment]
Okay I installed python now plz tell me what to do?

**Comment by kylemcdonald** [comment]
You'll also need to install tcpdump. It looks like it's called "[windump](http://www.winpcap.org/windump/)" on Windows. Then keep following the readme:

1. Install [Python pip](https://pip.pypa.io/en/stable/installing/)
2. Make a copy of this repository and install dependencies for the script:

```
$ git clone https://github.com/kylemcdonald/FreeWifi
$ cd FreeWifi && sudo pip install -r requirements.txt
```

Instead of "git clone" you can also [download the repo](https://github.com/kylemcdonald/FreeWifi/archive/master.zip) from the "Clone or download" button on the main page.

You might have a problem when it tries to install `netifaces`. Post a copy of the output in the command prompt when you get to that point. Better yet, go to [that repo](https://github.com/raphdg/netifaces) and post an issue.

Alternatively, you might get farther if you download a copy of Kali or Ubuntu and run it in a VM like Virtual Box, then continue by following the Linux instructions.

Good luck!

**Comment by vcidst** [comment]
Hello,

Thanks for this repo, I tried what you suggest and was able to install the packages just fine. However, I get an error when running `python wifi-users.py`

```
(base) C:\Code\Github\FreeWifi>pip install -r requirements.txt
Collecting netifaces (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/56/e9/bdac3b8fb0349f7aa0323ed8304175309f10be48ef6e2f6166578af2f136/netifaces-0.10.9-cp37-cp37m-win_amd64.whl
Collecting netaddr (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 142kB/s
Collecting wireless (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/16/0f/dbcf07fc0b28fd034a364156d7ddd7ed01079a2b904b29f0ad017238e55c/wireless-0.3.2.tar.gz
Collecting SpoofMAC (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/9c/59/cc52a4c5d97b01fac7ff048353f8dc96f217eadc79022f78455e85144028/SpoofMAC-2.1.1.tar.gz
Requirement already satisfied: tqdm in c:\users\zscore\anaconda3\lib\site-packages (from -r requirements.txt (line 5)) (4.28.1)
Collecting docopt (from SpoofMAC->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Building wheels for collected packages: wireless, SpoofMAC, docopt
  Running setup.py bdist_wheel for wireless ... done
  Stored in directory: C:\Users\zscore\AppData\Local\pip\Cache\wheels\89\95\f3\b15ddb8de4d4e8280a4f2d535e6c25b473dd1d8049ff7d7f00
  Running setup.py bdist_wheel for SpoofMAC ... done
  Stored in directory: C:\Users\zscore\AppData\Local\pip\Cache\wheels\87\ee\8c\4f0dffb7b6b7286d67796b270fbfaf659009119a152d4f3d93
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: C:\Users\zscore\AppData\Local\pip\Cache\wheels\9b\04\dd\7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
Successfully built wireless SpoofMAC docopt
Installing collected packages: netifaces, netaddr, wireless, docopt, SpoofMAC
Successfully installed SpoofMAC-2.1.1 docopt-0.6.2 netaddr-0.7.19 netifaces-0.10.9 wireless-0.3.2

(base) C:\Code\Github\FreeWifi>python wifi-users.py
Error getting wireless interface.
Traceback (most recent call last):
  File "wifi-users.py", line 161, in <module>
    main(argv)
  File "wifi-users.py", line 58, in main
    wireless = Wireless()
  File "C:\Users\zscore\Anaconda3\lib\site-packages\wireless\Wireless.py", line 23, in __init__
    self._driver_name = self._detectDriver()
  File "C:\Users\zscore\Anaconda3\lib\site-packages\wireless\Wireless.py", line 50, in _detectDriver
    compare = self.vercmp(ver, "0.9.9.0")
  File "C:\Users\zscore\Anaconda3\lib\site-packages\wireless\Wireless.py", line 71, in vercmp
    return cmp(normalize(actual), normalize(test))
NameError: name 'cmp' is not defined
```

I notice the error isn't really from your code but the package wireless. I checked their issue pages and it seems that [it is currently an open issue](https://github.com/joshvillbrandt/wireless/issues/32) -- does your repo work with Python 3.x?
